### ISSUE TITLE
Link isn't redirecting properly to the blog post

### ISSUE THREAD

**Issue by FahimFBA** [varunsridharan/action-hashnode-blog#4]
**Describe the bug**
The blog post isn't redirecting to the original URL; hence getting error. It is adding `-ckv5ezyn119lrsss12d72h1qm` extra at the end of the URL.

**To Reproduce**
1. Go to the readme
2. Click on any blogpost
3. See error

**Expected behavior**
It should redirect to the original blog post

**Screenshots**

![Screenshot 2022-04-28 094901](https://user-images.githubusercontent.com/64195132/165672602-3d86a50e-8008-4ec3-8a7e-0cab3a4e9a0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.127 (Official Build) (64-bit)

**Additional context**
Nope

**Comment by varunsridharan** [comment]
can you please share a link that throws 404 ?

**Comment by FahimFBA** [comment]
Sure! This is the repo where I used the action: https://github.com/FahimFBA/FahimFBA

The action is working like below:

```
<!-- HASHNODE_BLOG:START -->
- [Make your Linux OS ready for GitHub, GitLab & BitBucket altogether](https://fahimfba.hashnode.dev/make-your-linux-os-ready-for-github-gitlab-and-bitbucket-altogether-ckv5ezyn119lrsss12d72h1qm)
<!-- HASHNODE_BLOG:END -->
```

But the link should be: https://fahimfba.hashnode.dev/make-your-linux-os-ready-for-github-gitlab-and-bitbucket-altogether

It's taking my Hashnode username instead of the blogname (fahimbinamin).

**Comment by FahimFBA** [comment]
I fixed the issue by adding the blog URL. Thus, I am closing the issue.
