### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [varunsridharan/action-hashnode-blog#6]
**Describe the bug**
When I create a new file called `hashnode.yml` and add its content and add 2 blocks and commit it doesn't give me a error or any of that

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varunsridharan** [comment]
@Programming-School-Pro-Coding after adding the file you need to run the action once to get the blogs updated in readme file 
https://github.com/Programming-School-Pro-Coding/Programming-School-Pro-Coding/actions/workflows/hashnode.yml

or you can wait till action gets automatically triggered every day at 12AM

**Comment by varunsridharan** [comment]
@Programming-School-Pro-Coding please check the video here to understand how to run it manually
https://s2.do-spaces.com/2022/Jun/07/165459176841.mp4
