### ISSUE TITLE
Action running on Node.js 12 and deprecating soon.

### ISSUE THREAD

**Issue by Pradumnasaraf** [varunsridharan/action-hashnode-blog#9]
Hey @varunsridharan 

Do you plan to upgrade the action to make it compatible with Node.js 16 or 18? As 12 is deprecating soon

<img width="1161" alt="Screenshot 2023-01-18 at 4 31 41 PM" src="https://user-images.githubusercontent.com/51878265/213155535-d695119e-12fa-41e9-b22b-1752a2fb9687.png">

Thank you.

**Comment by varunsridharan** [comment]
Will update it very soon

**Comment by Pradumnasaraf** [comment]
> Will update it very soon

Amazing. Thank you for the fast response.

**Comment by Pradumnasaraf** [comment]
Hey, @varunsridharan,

It look like Actions is failing for some reason also any plan on updating the Node version?

<img width="1501" alt="Screenshot 2023-05-09 at 10 16 07 AM" src="https://user-images.githubusercontent.com/51878265/236996532-4c51a743-641c-485b-bbd7-c175d263cb2c.png">

**Comment by varunsridharan** [comment]
@Pradumnasaraf it seems like some changes has been made with hashnode api and i am working on it to get it back online.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf it seems like some changes has been made with hashnode api and i am working on it to get it back online.

Awesome. Thank you.

**Comment by varunsridharan** [comment]
@Pradumnasaraf issue fixed and node js updated & released new version

**Comment by Pradumnasaraf** [comment]
Awesome. It's working great. Thanks for updating it.

Just one thing. Do you think with the new update we have an extra `<br>` that cause a little bit more extra spacing?

<img width="893" alt="Screenshot 2023-05-10 at 11 09 02 AM" src="https://github.com/varunsridharan/action-hashnode-blog/assets/51878265/7e26f341-de4a-4af0-9b94-b49b96e928c9">
